#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  disabled_plugins = []
  enable_gcm = false
  relativenumber = false
  bootstrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'
  autocomplete_method = 'deoplete'
  
  # layer: checkers
  enable_neomake = false
  enable_ale = true

  # layer: chinese
  vim_help_language = "cn"

  # layer: colorscheme
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "onedark"
  colorscheme_bg = "dark"

  # layer: core#statusline
  # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以禁用分割符号，
  # 分割符包括以下几种 "arrow", "curve", "slant", "fire", "nil"，默认为箭头 "arrow"
  # 设置活动窗口状态栏上的分割符号形状
  statusline_separator = "arrow"
  # 设置非活动窗口状态栏上的分割符号形状
  statusline_inactive_separator = "arrow"
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
  # 0: 1 ➛ ➊
  # 1: 1 ➛ ➀
  # 2: 1 ➛ ⓵
  # 3: 1 ➛ ¹
  # 4: 1 ➛ 1
  buffer_index_type = 1
  # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
  enable_statusline_mode = false

  # layer: core#tabline
  enable_tabline_filetype_icon = true

  # layer: core
  filemanager = "nerdtree"


# Enable VersionControl
[[layers]]
  name = 'VersionControl'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "smart"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'checkers'
  lint_on_the_fly = true

[[layers]]
  name = 'chinese'

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'core'
  filetree_show_hidden = true

[[layers]]
  name = 'format'

[[layers]]
  name = 'git'

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#go'

[[layers]]
  name = 'lang#html'

[[layers]]
  name = 'lang#javascript'
  auto_fix = true
  enable_flow_syntax = false

[[layers]]
  name = 'lang#php'

[[layers]]
  name = 'lang#typescript'

[[layers]]
  name = 'lang#vim'

[[layers]]
  name = 'lang#vue'

[[layers]]
  name = 'lsp'
  filetypes = [
    'css',
    'html',
    'javascript',
    'php',
    'sh',
    'typescript',
    'vue'
  ]

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'tmux'

[[layers]]
  name = 'ui'

